FROM centos/devtoolset-6-toolchain-centos7
LABEL com.vfxplatform.version="CY2018"

ENV ASWF_BUILD_DIR /tmp/vfx-build
ENV ASWF_ROOT_DIR /opt/aswf/vfx2018

USER root

RUN mkdir -p $ASWF_BUILD_DIR && \
    mkdir -p $ASWF_ROOT_DIR

RUN yum install -y \
    bzip2-devel \
    file \
    make \
    python-devel \
    which \
    zlib-devel 

RUN curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" &&\
    python get-pip.py

RUN pip install \
    conan \
    numpy==1.12.1

RUN curl "https://cmake.org/files/v3.12/cmake-3.12.3-Linux-x86_64.sh" -o "cmake-3.12.3-Linux-x86_64.sh" &&\
    sh cmake-3.12.3-Linux-x86_64.sh --skip-license

ADD config /tmp/conan-config
RUN conan config install /tmp/conan-config

WORKDIR $ASWF_ROOT_DIR
